# 是否fpt文件优先
fpt_priority: False

# 每次删除图数量
delete_plots_num_per_time: 2

# 磁盘挂载根目录
drive_root_path: "/srv/"
# 磁盘文件夹标识（用于排除磁盘挂载根目录下排除无效目录，可为填""，则不作排除）
drive_character: "disk"

# chia图目录名
plots_dir: "chiapp-files" # 如果为空"",则不删图
# nossd图目录名
nossd_dir: "nossd"
# hpool服务名
hpool_service: "hpoolpp" # 如果为空"",则删图前不考虑hpool独占
# nossd服务名
nossd_service: "nossd"

# nossd安装文件目录
nossd_path: "/root/install/nossd-1.2/"
# nossd脚本名
nossd_start_sh: "start.sh"

# nossd压缩等级
nossd_type: 5
# nossd机器名
nossd_name: "bsh_001"
# nossd收益地址
nossd_address: "xch1m49h6ny95xgs5a3p2wg6ghnr3vejsqq2pwklq9ae8kg8wgkfujcs26djuq"
# nossd临时文件磁盘
nossd_tmp_drive_paths: 
  - "/srv/dev-disk-by-uuid-9802c526-c5e2-44a4-9e29-b7e1b7b805a0"
  - "/srv/dev-disk-by-uuid-ffeb0e19-8f2a-453a-abec-9aa7884c1124"
  - "/srv/dev-disk-by-uuid-0ee42af9-6cc1-41a3-992c-c7a80a764b01"
  
# 等待检查间隔(s)
waitting_time: 300
